"""Add role column

Revision ID: daf252cb3ffd
Revises: 885a6dbb954b
Create Date: 2024-11-19 18:40:20.882591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf252cb3ffd'
down_revision: Union[str, None] = '885a6dbb954b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('role', sa.String(), server_default='', nullable=False))
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'role')
    # ### end Alembic commands ###
